eshop/eshop/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/', include('users.urls', namespace='user')),
    url(r'^shop/', include('shop.urls', namespace='shop')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^search/', include('haystack.urls')),
    url(r'^shop_cart/', include('shop_cart.urls', namespace='shop_cart')),
    url(r'^shop_order/', include('shop_order.urls', namespace='shop_order')),
    # url('^search/$', MySearchView.as_view())
]


















# if settings.DEBUG:
#    urlpatterns += patterns('', url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT }),
#         url(r'^static/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.STATIC_ROOT}), )

eshop/shop/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2017/7/5 19:01
# @Author  : zhl
# @Site    : 
# @File    : urls.py
# @Software: PyCharm
from django.conf.urls import url
from shop import views
from .search_view import MySearchView
urlpatterns = [
    url(r'^index/$', views.IndexView.as_view(), name='index'),
    url(r'^detail/(?P<nid>\d*)/$', views.DetailView.as_view(), name='detail'),
    url(r'^list/(?P<nid>\d*)/$', views.ListView.as_view(), name='list'),
    url(r'^list_check/(?P<nid>\d*)-(?P<current_page>\d*)-(?P<ordering>\d*)/$', views.ListCheckView.as_view(), name='list_check'),

]

eshop/shop_cart/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2017/7/11 11:39
# @Author  : zhl
# @Site    : 
# @File    : urls.py
# @Software: PyCharm
from django.conf.urls import url

from shop_cart import views
urlpatterns = [
    url(r'^add_cart/(?P<nid>\d*)/$', views.AddCartView.as_view(), name='add_cart'),
    url(r'^update_cart/(?P<nid>\d*)/$', views.UpdateCartview.as_view(), name='update_cart'),
    url(r'^delete_goods/(?P<nid>\d*)/$', views.DeleteGoodsView.as_view(), name='delete_goods'),
    url(r'^order/$', views.OrderView.as_view(), name='order'),
    url(r'^my_cart/$', views.MyCartView.as_view(), name='my_cart'),
]

eshop/user/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2017/7/4 22:35
# @Author  : zhl
# @Site    : 
# @File    : urls.py
# @Software: PyCharm
from django.conf.urls import url
from user import views
urlpatterns = [
    url(r'user_center_info', views.UserCenterInfoView.as_view(), name='user_center_info'),
    url(r'register', views.RegisterView.as_view(), name='register'),
]

eshop/users/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2017/7/5 10:34
# @Author  : zhl
# @Site    : 
# @File    : urls.py
# @Software: PyCharm
from django.conf.urls import url
from users import views

urlpatterns = [
    url(r'^register/$', views.RegisterView.as_view(), name='register'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^check_username/$', views.check_username, name='check_username'),
    url(r'^user_center_info/$', views.UserCenterInfoView.as_view(), name='user_center_info'),
    url(r'^user_center_order/$', views.UserCenterOrderView.as_view(), name='user_center_order'),
    url(r'^user_center_site/$', views.UserCenterSiteView.as_view(), name='user_center_site'),
    # 删除用户的收获地址url
    url(r'^modify_address/$', views.ModifyAddressView.as_view(), name='modify_address'),
    # 邮箱激活验证  修改密码等操作
    url(r'^active/(?P<active_code>.*)/$', views.ActiveView.as_view(), name='active'),
    url(r'^send_success/$', views.SendSuccessView.as_view(), name='send_success'),
    url(r'^forget_password/$', views.ForgePasswordView.as_view(), name='forget_password'),
    url(r'^reset/(?P<reset_code>.*)/$', views.ResetPasswordView.as_view(), name='reset'),
    url(r'^modify_password/$', views.ModifyView.as_view(), name='modify_password'),
]

eshop/shop_order/models.py
from django.db import models
from users.models import UserProfile
from shop.models import GoodsInfo


# Create your models here.
class OrderMain(models.Model):
    # 1 2 3 4
    order_statue = (
        ('0', '未支付'),
        ('1', '已支付'),
        ('2', '已发货'),
        ('3', '待发货'),
    )
    # orderid = models.CharField(max_length=20, primary_key=True, unique=True,verbose_name='订单编号')  # 20170713000000用户id
    order_id = models.CharField(max_length=20, unique=True,verbose_name='订单编号')  # 20170713000000用户id
    order_time = models.DateTimeField(auto_now_add=True, verbose_name='提交订单时间')
    pay_time = models.DateTimeField(null=True,blank=True, verbose_name='付款时间')
    user = models.ForeignKey(UserProfile, verbose_name='购买的用户')
    total = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='总价格')
    is_pay = models.CharField(max_length=5, choices=order_statue, default="0", verbose_name='订单状态')

    class Meta:
        verbose_name = '订单中心'
        verbose_name_plural = verbose_name
        ordering = ('-id',)

    def __str__(self):
        return str(self.user) + str(self.order_id)


class OrderDetail(models.Model):
    order = models.ForeignKey(OrderMain, verbose_name='订单中心')
    goods_info = models.ForeignKey(GoodsInfo, verbose_name='商品')
    goods_price = models.DecimalField(max_digits=5, decimal_places=2, verbose_name='商品价格')
    count = models.IntegerField(verbose_name='购买商品的数量')

    class Meta:
        verbose_name = '订单详情'
        verbose_name_plural = verbose_name
        ordering = ('-id',)

    def __str__(self):
        return str(self.order) + str(self.goods_info)

eshop/users/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2017/7/5 11:36
# @Author  : zhl
# @Site    : 
# @File    : forms.py
# @Software: PyCharm
from django import forms

class RegisterForm(forms.Form):
    """验证用户注册"""
    username = forms.CharField(required=True)
    password1 = forms.CharField(required=True)
    password2 = forms.CharField(required=True)
    email = forms.EmailField(required=True, error_messages={'invalid':"不是一个有效的邮箱地址"})

class LoginForm(forms.Form):
    """登陆验证"""
    username = forms.CharField(required=True)
    password = forms.CharField(required=True)


class ReceiverForm(forms.Form):
    """登陆验证"""
    username = forms.CharField(required=True)
    city = forms.CharField(required=True)
    telephone = forms.CharField(required=True)
    address = forms.CharField(required=True)


class ModifyForm(forms.Form):
    """登陆验证"""
    password1 = forms.CharField(required=True)
    password2 = forms.CharField(required=True)

eshop/users/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.views.generic import View
from django.contrib.auth.models import make_password
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.backends import ModelBackend
from django.utils.decorators import method_decorator
from django.db.models import Q
from django.contrib import messages

from .models import UserProfile, Receiver, EmailVerifyRecord
from .forms import RegisterForm, LoginForm, ReceiverForm, ModifyForm
from utils.email_send import send_email
from utils.use_redis import UseRedis
from utils.get_page import get_page

from .decorate import check_auth
from shop.models import GoodsInfo
from shop_order.models import OrderMain


# Create your views here.



def check_username(request):
    """接受ajax请求验证用户名是否是存在的"""
    username = request.GET.get('username')
    count = UserProfile.objects.filter(username=username).count()
    return JsonResponse({"count": count})


def user_logout(request):
    """注销函数"""
    logout(request)
    # del request.session['user_id']
    # del request.session['username']

    return redirect('/shop/index/')


class CustomBackend(ModelBackend):
    """验证用户可以使用邮箱,电话登陆"""

    def authenticate(self, username=None, password=None, **kwargs):
        try:
            user = UserProfile.objects.get(Q(username=username) | Q(email=username) | Q(telephone_number=username))
            if user.check_password(password):
                return user
        except:
            return None


class RegisterView(View):
    """用户注册视图类"""

    def get(self, request):
        return render(request, 'user/register.html')

    def post(self, request):
        user = UserProfile()
        register_form = RegisterForm(request.POST)
        if register_form.is_valid():
            return self.save_register_info(request, user)
        else:
            return render(request, 'user/register.html', locals())

    def save_register_info(self, request, user):
        """保存用户注册的信息"""
        username = request.POST.get('username')
        email = request.POST.get('email')
        # 在后台再次判断 邮箱和用户名是否已经存在  存在就返回
        if UserProfile.objects.filter(Q(username=username) | Q(email=email)):
            err = "用户名或者邮箱已经存在"
            return render(request, 'user/register.html', locals())
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        allow = request.POST.get('allow')
        if password1 != password2 or allow != '1':
            err = '两次输入的密码一致'
            err_allow = "请阅读用户使用协议"
            return render(request, 'user/register.html', locals())

        user.username = username
        user.password = make_password(password1)
        user.email = email
        user.is_active = False
        user.save()
        send_email(email, send_type="注册")
        return redirect('/user/send_success/')


class LoginView(View):
    """登陆视图"""

    def get(self, request):
        username = request.COOKIES.get('username', "")
        return render(request, 'user/login.html', locals())

    def post(self, request):
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                return self.check_user(request, user, username)  # 调用设置cookie的函数
            else:
                err = "用户名或者密码错误.."
                return render(request, 'user/login.html', locals())
        else:
            return render(request, 'user/login.html', locals())

    def check_user(self, request, user, username):
        """处理用用户的cookie信息"""
        if user.is_active:
            login(request, user)
            request.session['user_id'] = user.id  # 获取用户的id保存在信息中
            request.session['username'] = username  # 把用户名保存在session中 用来在前端进行是否登陆验证
            url_path = request.session.get('url_path')  # 通过中间件来完成原页面的跳转
            print("登陆成功后的从", url_path)
            if url_path:
                response = redirect(url_path)
            else:
                response = redirect('/shop/index/')
            if request.POST.get('checkbox') == '1':
                response.set_cookie('username', username)  # 设定cookie
            elif request.POST.get('checkbox') == None:
                response.delete_cookie('username')  # 删除cookie
            return response
        else:
            err = "用户没有激活..请先去激活账户.."
            return render(request, 'user/login.html', locals())


class UserCenterInfoView(View):
    """用户信息中心信息视图类"""

    @method_decorator(check_auth)
    def get(self, request):
        url_id = request.GET.get('url_id')  # 控制用户中心的高高亮
        user_id = request.session.get('user_id')  # 获取用户的id 来区分不同的用户 在redis中
        recently_browsed = UseRedis.read_from_cache(user_id, 'recently_browsed')
        if recently_browsed is not None:
            recently_browsed_list = []
            for item in recently_browsed:
                recently_browsed_list.append(GoodsInfo.objects.get(id=item))
        try:
            user_id = request.session.get('user_id')
            user_info_list = UserProfile.objects.get(id=user_id)
            return render(request, 'user/user_center_info.html', locals())
        except Exception as err:
            # TODO 这里怎么把 通过redirect  把错误的信息带回去  也就是 解决通过后台进行登陆的是后 拿不到session中的值
            return redirect('/user/login/')


class UserCenterOrderView(View):
    """用户订单信息视图类"""

    @method_decorator(check_auth)
    def get(self, request):
        url_id = request.GET.get('url_id')  # 控制用户中心的高高亮
        user_id = request.session.get('user_id')
        current_page = int(request.GET.get('page',1))
        order_main = OrderMain.objects.filter(user_id=user_id)
        current_page_order_inf0, page_range = get_page(order_main, current_page, 1)
        return render(request, 'user/user_center_order.html', locals())




class UserCenterSiteView(View):
    """用户信息中心信息视图类"""

    def get_user(self, request):
        """获取用户的信息"""

        user_id = request.session.get('user_id')
        user_info_list = UserProfile.objects.get(id=user_id)  # 获取当前用户的信息
        receiver_info = Receiver.objects.filter(user=user_info_list)  # 返回收货人信息
        return user_info_list, receiver_info

    @method_decorator(check_auth)
    def get(self, request):
        url_id = request.GET.get('url_id')  # 控制用户中心的高高亮
        user_info_list, receiver_info = self.get_user(request)
        return render(request, 'user/user_center_site.html', locals())

    def post(self, request, ):
        url_id = request.GET.get('url_id')  # 控制用户中心的高高亮
        user_info_list, receiver_info = self.get_user(request)
        receiver_form = ReceiverForm(request.POST)
        if receiver_form.is_valid():
            self.receiver_save_model(request, user_info_list)
            # TODO 这里该为使用ajax来进行提交 只刷新表单的部分
            return render(request, 'user/user_center_site.html', locals())
        else:
            print(receiver_form.errors)
            return render(request, 'user/user_center_site.html', locals())

    def receiver_save_model(self, request, user_info_list):
        """保存增加收货人的信息"""
        receiver = Receiver()
        receiver.user = user_info_list  # 获取关联的对象  收货人的信息
        receiver.name = request.POST.get('username')
        receiver.city = request.POST.get('city')
        receiver.address = request.POST.get('address')
        receiver.telephone = request.POST.get('telephone')
        receiver.save()
        # 使用消息框架通知用户增加成功  配合使用信号 来通知 数据库添加删除成功on个  然后根据结果来发送不同的的消息
        messages.success(request, '添加成功')


class ModifyAddressView(View):
    """操作收货地址 对地址进行编辑和删除操作"""

    @method_decorator(check_auth)
    def get(self, request):
        # 先去获取当前的用户
        # TODO 把user_id 融合到url中 不在显示在get提交的路径上了
        user_id = request.session.get('user_id')
        user = UserProfile.objects.get(id=user_id)
        if request.is_ajax():
            return self.ajax_post(request, user)  # 调用ajax请求的方法
        receiver_user_id = request.GET.get("id")
        receiver = Receiver.objects.filter(user=user_id)  # 这里使用的是获取到的是id的在关联表中 存的也是id的值
        receiver.filter(id=receiver_user_id).delete()
        # TODO 考虑使用ajax 请求 请求成功后  在前端 进行重定向
        return redirect('/user/user_center_site/')  # 在去请求这个页面 进行页面的刷新 返回

    def ajax_post(self, request, user):
        """修改默认的收货地址"""
        name = request.GET.get('name')
        telephone = request.GET.get('telephone')
        address = request.GET.get('address').strip()
        user.receiver_name = name
        user.telephone_num = telephone
        user.address = address
        user.save()
        content = {'name': name, 'telephone': telephone, 'address': address}
        return JsonResponse(content)


class SendSuccessView(View):
    """发送邮件成功"""

    def get(self, request):
        return render(request, 'user/send_success.html')


class ActiveView(View):
    """邮箱激活"""

    def get(self, request, active_code):
        verify_code = EmailVerifyRecord.objects.filter(code=active_code).first()
        if verify_code is not None:
            email = verify_code.email  # 获取用户的邮箱这样才能知道这个是谁的账户
            user = UserProfile.objects.filter(email=email).first()
            user.is_active = True  # 账户设置为可用
            user.save()
            return redirect('/user/login/')  # 验证成功跳转到登陆页面
        else:
            # 验证失败返回忘记密码页面
            return render(request, 'user/active.html')


class ForgePasswordView(View):
    """忘记密码"""

    def get(self, request):
        return render(request, 'user/forget_password.html')

    def post(self, request):
        email = request.POST.get('email')
        user = UserProfile.objects.filter(email=email).first()
        if user:
            statue = send_email(email, send_type="忘记密码")
            if statue:
                return redirect('/user/send_success/')  # 跳转到邮箱发送成功的页面
            else:

eshop/templates/user/active.html
{% extends 'base.html' %}

{% block title %}天天生鲜-登录{% endblock title %}
{% block content %}
    <h3>连接失效....</h3>
{% endblock content %}

eshop/templates/user/edite_address.html
<!-- Modal -->
<div class="modal fade" id="myModal_1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">修改收获人信息</h4>
            </div>
            <div class="modal-body">
                <form action="{% url 'user:user_center_site' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="">收货人</label>
                        <input type="text" name="username" class="form-control" placeholder="请填写收货人" value="{{ info.name }}">
                    </div>
                    <div class="form-group">
                        <label for="">城市</label>
                        <input type="text" name="city" class="form-control" placeholder="填写所在城市">
                    </div>
                    <div class="form-group">
                        <label for="">联系电话</label>
                        <input type="text" name="telephone" class="form-control" placeholder="填写有效的练习电话">
                    </div>
                    <div class="form-group">
                        <label for="">详细地址</label>
                        <textarea name="address" class="form-control" cols="7" rows="3"
                                  placeholder="请填写详细的地址"></textarea>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">取&nbsp;&nbsp;消</button>
                        <button type="submit" class="btn btn-primary">确&nbsp;&nbsp;定</button>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>

eshop/templates/user/forget_password.html
{% extends 'base.html' %}

{% block title %}天天生鲜-忘记密码{% endblock title %}
{% block header %}

{% endblock header%}
{% block content %}
    <div class="login_top clearfix">
        <a href="index.html" class="login_logo"><img src="{{ STATIC_URL }}images/logo02.png"></a>
    </div>

    <div class="login_form_bg">
        <div class="login_form_wrap clearfix">
            <div class="login_banner fl"></div>
            <div class="slogan fl">日夜兼程 · 急速送达</div>
            <div class="login_form fr">
                <div class="login_title clearfix">
                    <h1>忘记密码</h1>
                    <a href="{% url 'user:login' %}">登陆</a>
                </div>
                <div class="form_input">
                    <form action="{% url 'user:forget_password' %}" method="post">
                        {% csrf_token %}
                        <input type="email" name="email" class="name_input" placeholder="请输入注册邮箱"
                               value="{{ login_form.email.value }}">
                        <input type="text" name="yanzhengma" class="pass_input" placeholder="请输入验证码"
                               value="{{ login_form.password.value }}">
                        <input type="submit" name="" value="提交申请" class="input_submit">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

eshop/templates/user/login.html
{% extends 'base.html' %}

{% block title %}天天生鲜-登录{% endblock title %}
{% block header %}

{% endblock header%}
{% block content %}
    <div class="login_top clearfix">
        <a href="index.html" class="login_logo"><img src="{{ STATIC_URL }}images/logo02.png"></a>
    </div>

    <div class="login_form_bg">
        <div class="login_form_wrap clearfix">
            <div class="login_banner fl"></div>
            <div class="slogan fl">日夜兼程 · 急速送达</div>
            <div class="login_form fr">
                <div class="login_title clearfix">
                    <h1>用户登陆</h1>
                    <a href="{% url 'user:register' %}">注册</a>
                </div>
                <div class="form_input">
                    <form action="{% url 'user:login' %}" method="post">
                        {% csrf_token %}
                        <input type="text" name="username" class="name_input" placeholder="请输入用户名"
                               value="{{ username }}">
                        <div class="user_error" style="display: block">
                            {% if login_form.errors.username %}
                                {{ login_form.errors.username.0 }}
                            {% endif %}
                        </div>
                        <input type="password" name="password" class="pass_input" placeholder="请输入密码"
                               value="{{ login_form.password.value }}">
                        <div class="pwd_error" style="display: block">
                            {% if login_form.errors.password %}
                                {{ login_form.errors.passwrod.0 }}
                                {% else %}
                                {{ err }}
                            {% endif %}
                        </div>
                        <div class="errs">{{ err }}</div>
                        <div class="more_input clearfix">
                            <input type="checkbox" name="checkbox" value="1" checked="checked">
                            <label>记住用户名</label>
                            <a href="{% url 'user:forget_password' %}">忘记密码</a>
                        </div>
                        <input type="submit" name="" value="登录" class="input_submit">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

eshop/templates/user/register.html
{% extends 'base.html' %}
{% block title %}欢迎注册{% endblock title %}
{% block js %}
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery-1.12.4.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/register.js"></script>
{% endblock js %}
{% block header %}

{% endblock header%}
{% block content %}
    <div class="register_con">
        <div class="l_con fl">
            <a class="reg_logo"><img src="{{ STATIC_URL }}images/logo02.png"></a>
            <div class="reg_slogan">足不出户 · 新鲜每一天</div>
            <div class="reg_banner"></div>
        </div>

        <div class="r_con fr">
            <div class="reg_title clearfix">
                <h1>用户注册</h1>
                <a href="{% url 'user:login' %}">登录</a>
            </div>
            <div class="reg_form clearfix">
                <form action="{% url 'user:register' %}" method="post" id="reg_form">
                    {% csrf_token %}
                    <ul>
                        <li>
                            <label>用户名:</label>
                            <input type="text" name="username" id="user_name" value="{{ register_form.username.value }}">
                            <span class="error_tip" {% if register_form.errors.email %} style="display: block" {% endif %} >{{ register_form.errors.username.0 }}</span>
                        </li>
                        <li>
                            <label>密码:</label>
                            <input type="password" name="password1" id="pwd" value="{{ register_form.password1.value }}">
                            <span class="error_tip" {% if register_form.errors.email %} style="display: block" {% endif %} >{{ register_form.errors.password1.0 }}</span>
                        </li>
                        <li>
                            <label>确认密码:</label>
                            <input type="password" name="password2" id="cpwd" value="{{ register_form.password2.value }}">
                            <span class="error_tip" {% if register_form.errors.email %} style="display: block" {% endif %}>{{ register_form.errors.password2.0 }}</span>
                        </li>
                        <li>
                            <label>邮箱:</label>
                            <input type="text" name="email" id="email" value="{{ register_form.email.value }}">
                            <span  class="error_tip" {% if register_form.errors.email %} style="display: block" {% endif %}>{{  register_form.errors.email.0 }}</span>
                        </li>
                        <li class="agreement">
                            <input type="checkbox" name="allow" id="allow" checked="checked" value="1">
                            <label>同意”天天生鲜用户使用协议“</label>
                            <span class="error_tip2" {% if err_allow %} style="display: block" {% endif %}>{{ err_allow }}</span>
                        </li>
                        <li class="reg_sub">
                            <input type="submit" value="注 册" name="">
                        </li>
                    </ul>
                </form>
            </div>

        </div>

    </div>
{% endblock content %}

eshop/templates/user/reset_password.html
{% extends 'base.html' %}

{% block title %}天天生鲜-重置密码{% endblock title %}
{% block header %}

{% endblock header %}
{% block content %}
    <div class="login_top clearfix">
        <a href="index.html" class="login_logo"><img src="{{ STATIC_URL }}images/logo02.png"></a>
    </div>

    <div class="login_form_bg">
        <div class="login_form_wrap clearfix">
            <div class="login_banner fl"></div>
            <div class="slogan fl">日夜兼程 · 急速送达</div>
            <div class="login_form fr">
                <div class="login_title clearfix">
                    <h1>密码重置</h1>
                    <a href="{% url 'user:login' %}">登陆</a>
                </div>
                <div class="form_input">
                    <form action="{% url 'user:modify_password' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="email" value="{{ email }}">
                        <input type="password" name="password1" class="name_input" placeholder="请输入密码"
                        >
                        <input type="password" name="password2" class="pass_input" placeholder="请再次输入密码"
                        >
                        <input type="submit" name="" value="确定" class="input_submit">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

eshop/templates/user/send_success.html
{% extends 'base.html' %}
{% block title %}
发送邮件
{% endblock title %}

{% block content %}
邮件发送成功,请及时去邮箱验证...
{% endblock content %}

eshop/templates/user/user_center_info.html
{% extends 'user_base.html' %} {% block user_content %}
    <div class="right_content clearfix">
        <div class="info_con clearfix">
            <h3 class="common_title2">基本信息</h3>
            <ul class="user_info_list">
                <li><span>用户名：</span>{{ user_info_list.username }}</li>
                <li><span>联系方式：</span>{{ user_info_list.telephone_number }}</li>
                <li><span>联系地址：</span>{{ user_info_list.address }}</li>
            </ul>
        </div>

        <h3 class="common_title2">最近浏览</h3>
        <div class="has_view_list">
            <ul class="goods_type_list clearfix">
                {% for goods in recently_browsed_list %}
                    <li>
                        <a href="{% url 'shop:detail' goods.id %}"><img src="{{ MEDIA_URL }}{{ goods.goods_images}}"></a>
                        <h4><a href="{% url 'shop:detail' goods.id %}">大兴大棚草莓</a></h4>
                        <div class="operate">
                            <span class="prize">￥{{ goods.goods_price }}</span>
                            <span class="unit">{{ goods.goods_price }}/{{ goods.goods_uint }}</span>
                            <a href="#" class="add_goods" title="加入购物车"></a>
                        </div>
                    </li>
                {% endfor %}

            </ul>
        </div>
    </div>
{% endblock user_content %}

eshop/templates/user/user_center_order.html
{% extends 'user_base.html' %}

{% block user_content %}
    <div class="right_content clearfix">
        <h3 class="common_title2">全部订单</h3>
        {% for item in current_page_order_inf0 %}
            <ul class="order_list_th w978 clearfix">
                <li class="col01">{{ item.order_time }}</li>
                <li class="col02">订单号：{{ item.order_id }}</li>
                <li class="col02 stress">{{ item.get_is_pay_display }}</li>
            </ul>


            <table class="order_list_table w980">
                <tbody>
                <tr>
                    <td width="55%">
                        {% for order_detail in item.orderdetail_set.all %}
                            <ul class="order_goods_list clearfix">
                                <li class="col01"><img src="{{ MEDIA_URL }}{{ order_detail.goods_info.goods_images }}">
                                </li>
                                <li class="col02">{{ order_detail.goods_info.goods_name|truncatechars:10 }}<em>{{ order_detail.price }}元/{{ order_detail.goods_info.goods_unit }}</em>
                                </li>
                                <li class="col03">{{ order_detail.count }}</li>
                                <li class="col04">{{ order_detail.goods_price }}元</li>
                            </ul>
                        {% endfor %}
                    </td>
                    <td width="15%"><em>{{ item.total }}</em>元</td>
                    <td width="15%">{{ item.get_is_pay_display }}</td>
                    <td width="15%"><a href="{% url 'shop_cart:my_cart' %}" class="oper_btn">去付款</a></td>
                </tr>

                </tbody>
            </table>

        {% empty %}
            <h3>暂时没有订单啊！！赶紧去买啊！！！</h3>
        {% endfor %}
        <div class="pagenation">
            {% if current_page_order_inf0.has_previous %}
                <a href="{% url 'user:user_center_order' %}?url_id=2&page={{ current_page_order_inf0.previous_page_number }}">
                    <上一页
                </a>
            {% endif %}
            {% for page_index in page_range %}
                <a href="{% url 'user:user_center_order' %}?url_id=2&page={{ page_index }}"
                   {% ifequal current_page page_index %}class="active"{% endifequal %}>{{ page_index }}</a>
            {% endfor %}

             {% if current_page_order_inf0.has_next %}
                <a href="{% url 'user:user_center_order' %}?url_id=2&page={{ current_page_order_inf0.next_page_number }}">
                    下一页>
                </a>
            {% endif %}
        </div>
    </div>

{% endblock user_content %}
