eshop/eshop/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/', include('users.urls', namespace='user')),
    url(r'^shop/', include('shop.urls', namespace='shop')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^search/', include('haystack.urls')),
    url(r'^shop_cart/', include('shop_cart.urls', namespace='shop_cart')),
    url(r'^shop_order/', include('shop_order.urls', namespace='shop_order')),
    # url('^search/$', MySearchView.as_view())
]


















# if settings.DEBUG:
#    urlpatterns += patterns('', url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT }),
#         url(r'^static/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.STATIC_ROOT}), )

eshop/shop/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2017/7/5 19:01
# @Author  : zhl
# @Site    : 
# @File    : urls.py
# @Software: PyCharm
from django.conf.urls import url
from shop import views
from .search_view import MySearchView
urlpatterns = [
    url(r'^index/$', views.IndexView.as_view(), name='index'),
    url(r'^detail/(?P<nid>\d*)/$', views.DetailView.as_view(), name='detail'),
    url(r'^list/(?P<nid>\d*)/$', views.ListView.as_view(), name='list'),
    url(r'^list_check/(?P<nid>\d*)-(?P<current_page>\d*)-(?P<ordering>\d*)/$', views.ListCheckView.as_view(), name='list_check'),

]

eshop/shop_cart/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2017/7/11 11:39
# @Author  : zhl
# @Site    : 
# @File    : urls.py
# @Software: PyCharm
from django.conf.urls import url

from shop_cart import views
urlpatterns = [
    url(r'^add_cart/(?P<nid>\d*)/$', views.AddCartView.as_view(), name='add_cart'),
    url(r'^update_cart/(?P<nid>\d*)/$', views.UpdateCartview.as_view(), name='update_cart'),
    url(r'^delete_goods/(?P<nid>\d*)/$', views.DeleteGoodsView.as_view(), name='delete_goods'),
    url(r'^order/$', views.OrderView.as_view(), name='order'),
    url(r'^my_cart/$', views.MyCartView.as_view(), name='my_cart'),
]

eshop/user/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2017/7/4 22:35
# @Author  : zhl
# @Site    : 
# @File    : urls.py
# @Software: PyCharm
from django.conf.urls import url
from user import views
urlpatterns = [
    url(r'user_center_info', views.UserCenterInfoView.as_view(), name='user_center_info'),
    url(r'register', views.RegisterView.as_view(), name='register'),
]

eshop/users/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2017/7/5 10:34
# @Author  : zhl
# @Site    : 
# @File    : urls.py
# @Software: PyCharm
from django.conf.urls import url
from users import views

urlpatterns = [
    url(r'^register/$', views.RegisterView.as_view(), name='register'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^check_username/$', views.check_username, name='check_username'),
    url(r'^user_center_info/$', views.UserCenterInfoView.as_view(), name='user_center_info'),
    url(r'^user_center_order/$', views.UserCenterOrderView.as_view(), name='user_center_order'),
    url(r'^user_center_site/$', views.UserCenterSiteView.as_view(), name='user_center_site'),
    # 删除用户的收获地址url
    url(r'^modify_address/$', views.ModifyAddressView.as_view(), name='modify_address'),
    # 邮箱激活验证  修改密码等操作
    url(r'^active/(?P<active_code>.*)/$', views.ActiveView.as_view(), name='active'),
    url(r'^send_success/$', views.SendSuccessView.as_view(), name='send_success'),
    url(r'^forget_password/$', views.ForgePasswordView.as_view(), name='forget_password'),
    url(r'^reset/(?P<reset_code>.*)/$', views.ResetPasswordView.as_view(), name='reset'),
    url(r'^modify_password/$', views.ModifyView.as_view(), name='modify_password'),
]

eshop/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>{% block title %}天天生鲜-用户中心{% endblock title %}</title>
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/reset.css">
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/main.css">
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery-1.12.4.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery-ui.min.js"></script>
    {% block css %}{% endblock css %}
    {% block js %}{% endblock js %}
</head>
<body>
{% block header %}
    <div class="header_con">
        <div class="header">
            <div class="welcome fl">欢迎来到天天生鲜!</div>
            <div class="fr">
                {% if request.user.is_authenticated %}
                    <div class="login_info fl" style="display: block">
                        欢迎您：<em>{{ request.user.username }}</em>
                    </div>
                {% else %}
                    <div class="login_btn fl" style="display: block">
                        <a href="{% url 'user:login' %}">登录</a>
                        <span>|</span>
                        <a href="{% url 'user:register' %}">注册</a>
                    </div>
                {% endif %}
                <div class="user_link fl">
                    <span>|</span>
                    <a href="{% url 'user:user_center_info' %}?url_id=1">用户中心</a>
                    <span>|</span>
                    <a href="{% url 'shop_cart:my_cart' %}">我的购物车</a>
                    <span>|</span>
                    <a href="{% url 'user:user_center_order' %}?url_id=2">我的订单</a>
                    <span>|</span>
                    <a href="{% url 'user:logout' %}">注销</a>
                </div>
            </div>
        </div>
    </div>
{% endblock header %}

{% block content %}
{% endblock content %}
<div class="footer">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
    <p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
    <p>电话：010-****888 京ICP备*******8号</p>
</div>

</body>
</html>`

eshop/templates/shop_base.html
{% extends 'base.html' %} {% block title %} 天天生鲜首页{% endblock title %} {% block js %}
    <script type="text/javascript" src="{{ STATIC_URL }}js/slide.js"></script>
{% block shop_js %}{% endblock shop_js %}
{% endblock js %} {% block content %}
    <div class="search_bar clearfix">
        <a href="{% url 'shop:index' %}" class="logo fl"><img src="{{ STATIC_URL }}images/logo.png"></a>
        <div class="search_con fl">
            <form method='get' action="/search/" target="_blank">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>

        </div>
        <div class="guest_cart fr">
            <a href="{% url 'shop_cart:my_cart' %}" class="cart_name fl">我的购物车</a>
            <div class="goods_count fl" id="show_count">{{ goods_num }}</div>
        </div>
    </div>
    {% block index_content %} {% block index_content_title %}
        <div class="navbar_con">
            <div class="navbar clearfix">
                <div class="subnav_con fl">
                    <h1>全部商品分类</h1>
                    <span></span>
                    <ul class="subnav">
                        <li><a href="{% url 'shop:list' category_list.0.id %}"
                               class="fruit">{{ category_list.0.category_name }}</a></li>
                        <li><a href="{% url 'shop:list' category_list.1.id %}"
                               class="seafood">{{ category_list.1.category_name }}</a></li>
                        <li><a href="{% url 'shop:list' category_list.2.id %}"
                               class="meet">{{ category_list.2.category_name }}</a></li>
                        <li><a href="{% url 'shop:list' category_list.3.id %}"
                               class="egg">{{ category_list.3.category_name }}</a></li>
                        <li><a href="{% url 'shop:list' category_list.4.id %}"
                               class="vegetables">{{ category_list.4.category_name }}</a></li>
                        <li><a href="{% url 'shop:list' category_list.5.id %}"
                               class="ice">{{ category_list.5.category_name }}</a></li>
                    </ul>
                </div>
                <ul class="navlist fl">
                    <li><a href="">首页</a></li>
                    <li class="interval">|</li>
                    <li><a href="">手机生鲜</a></li>
                    <li class="interval">|</li>
                    <li><a href="">抽奖</a></li>
                </ul>
            </div>
        </div>
    {% endblock index_content_title %} {% endblock index_content %} {% endblock content %}

eshop/templates/user_base.html
{% extends 'base.html' %} {% block title %}天天生鲜-用户中心 {% endblock title %}
{% block content %}
<div class="search_bar clearfix">
    <a href="{% url 'shop:index' %}" class="logo fl"><img src="{{STATIC_URL}}images/logo.png"></a>
    <div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{% block user_title %}用户中心{% endblock user_title %}</div>
    <div class="search_con fr">
        <input type="text" class="input_text fl" name="" placeholder="搜索商品">
        <input type="button" class="input_btn fr" name="" value="搜索">
    </div>
</div>
{% block user_center %}
<div class="main_con clearfix">
    <div class="left_menu_con clearfix">
        <h3>用户中心</h3>
        <ul>
        <li><a href="{% url 'user:user_center_info' %}?url_id=1" {% if  url_id == "1" %} class="active" {% endif %}>· 个人信息</a></li>
        <li><a href="{% url 'user:user_center_order' %}?url_id=2" {% if  url_id == "2" %} class="active" {% endif %}>· 全部订单</a></li>
        <li><a href="{% url 'user:user_center_site' %}?url_id=3" {% if  url_id  == "3" %} class="active" {% endif %}>· 收货地址</a></li>
        </ul>
    </div>
{% endblock user_center %}
    {% block user_content %} {% endblock user_content %}
</div>
{% endblock content %}