eshop/eshop/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/', include('users.urls', namespace='user')),
    url(r'^shop/', include('shop.urls', namespace='shop')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^search/', include('haystack.urls')),
    url(r'^shop_cart/', include('shop_cart.urls', namespace='shop_cart')),
    url(r'^shop_order/', include('shop_order.urls', namespace='shop_order')),
    # url('^search/$', MySearchView.as_view())
]


















# if settings.DEBUG:
#    urlpatterns += patterns('', url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT }),
#         url(r'^static/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.STATIC_ROOT}), )

eshop/shop/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2017/7/5 19:01
# @Author  : zhl
# @Site    : 
# @File    : urls.py
# @Software: PyCharm
from django.conf.urls import url
from shop import views
from .search_view import MySearchView
urlpatterns = [
    url(r'^index/$', views.IndexView.as_view(), name='index'),
    url(r'^detail/(?P<nid>\d*)/$', views.DetailView.as_view(), name='detail'),
    url(r'^list/(?P<nid>\d*)/$', views.ListView.as_view(), name='list'),
    url(r'^list_check/(?P<nid>\d*)-(?P<current_page>\d*)-(?P<ordering>\d*)/$', views.ListCheckView.as_view(), name='list_check'),

]

eshop/shop_cart/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2017/7/11 11:39
# @Author  : zhl
# @Site    : 
# @File    : urls.py
# @Software: PyCharm
from django.conf.urls import url

from shop_cart import views
urlpatterns = [
    url(r'^add_cart/(?P<nid>\d*)/$', views.AddCartView.as_view(), name='add_cart'),
    url(r'^update_cart/(?P<nid>\d*)/$', views.UpdateCartview.as_view(), name='update_cart'),
    url(r'^delete_goods/(?P<nid>\d*)/$', views.DeleteGoodsView.as_view(), name='delete_goods'),
    url(r'^order/$', views.OrderView.as_view(), name='order'),
    url(r'^my_cart/$', views.MyCartView.as_view(), name='my_cart'),
]

eshop/shop_cart/models.py
from django.db import models
from users.models import UserProfile
from shop.models import GoodsInfo


# Create your models here.
class ShopCart(models.Model):
    user = models.ForeignKey(UserProfile, verbose_name='购买用户')
    goods_info = models.ForeignKey(GoodsInfo, verbose_name='购买商品')
    count = models.IntegerField('购买数量')
    create_date_time = models.DateTimeField(auto_now=True, verbose_name='购买时间')

    class Meta:
        verbose_name = '购物车'
        verbose_name_plural = verbose_name
        ordering = ('-create_date_time',)

    def __str__(self):
        return str(self.goods_info)

eshop/shop_cart/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.views.generic import View
from django.utils.decorators import method_decorator

from utils.use_redis import UseRedis
from utils.my_logger import logger
from .models import ShopCart
from users.models import UserProfile
from users.decorate import check_auth


# Create your views here.

def save_total_num(buy_num, user_id):
    """把购物车中的购买商品的总量 存放在redis中"""
    total_num = UseRedis.read_from_cache(user_id, "total_num")  # 从redis中取出总数
    if total_num is None:
        total_num = 0
    total_num = total_num + buy_num
    UseRedis.write_to_cache(user_id, "total_num", total_num)  # 写入到redis中


class AddCartView(View):
    """添加商品到购物车"""

    def get(self, request, nid):
        user_id = request.session.get('user_id')  # 获取用户的信息 每个用户对应自己自己购买的商品
        if request.is_ajax():
            buy_num = request.GET.get('buy_num')
            if buy_num is not None:
                save_total_num(int(buy_num), user_id)
                try:
                    cart_obj = ShopCart.objects.filter(user_id=user_id, goods_info_id=nid).first()
                    if cart_obj:
                        cart_obj.count += int(buy_num)
                        cart_obj.save()
                    else:
                        ShopCart.objects.create(user_id=user_id, goods_info_id=nid, count=buy_num)
                    content = {'statue': "1"}
                except Exception as err:
                    logger.error(err)
                    content = {'statue': "0"}
            else:
                content = {'status': "0"}
            return JsonResponse(content)


class UpdateCartview(View):
    """更新数据库中的数量"""

    def get(self, request, nid):
        if request.is_ajax():
            user_id = request.session.get('user_id')  # 获取用户的信息 每个用户对应自己自己购买的商品
            buy_num = request.GET.get('buy_num')  # 获取购买的数量
            if buy_num is not None:
                buy_num = int(buy_num)
                try:
                    cart_obj = ShopCart.objects.filter(goods_info_id=nid).first()
                    before_goods_num = cart_obj.count  # 获取之前数据库中的数量然后计算更改的数量
                    cart_obj.count = buy_num
                    cart_obj.save()
                    change_num = buy_num - before_goods_num  # 计算增加的数量
                    save_total_num(change_num, user_id)
                    content = {'statue': "1"}
                except Exception as err:
                    logger.error(err)
                    content = {'statue': "0"}
            else:
                content = {'statue': "0"}
            return JsonResponse(content)


class DeleteGoodsView(View):
    """删除购物车中的商品"""

    def get(self, request, nid):
        user_id = request.session.get('user_id')
        if request.is_ajax():
            try:
                cart_obj = ShopCart.objects.filter(goods_info_id=nid).first()
                delete_num = (-cart_obj.count)
                cart_obj.delete()
                save_total_num(delete_num, user_id)
                content = {'statue': '1'}
            except Exception as err:
                logger.error(err)
                content = {'statue': '0'}
            return JsonResponse(content)


class OrderView(View):
    """订单页面"""

    @method_decorator(check_auth)
    def get(self, request):
        cart_id = request.session.get('cart_id')
        if cart_id is None:
            cart_id = []
        else:
            cart_id = cart_id.split('/')
        user_id = request.session.get('user_id')
        user = UserProfile.objects.filter(id=user_id).first()
        order_list = ShopCart.objects.filter(id__in=cart_id)
        content = {'order_list': order_list, 'user': user, 'cart_id': cart_id}
        return render(request, 'shop_cart/place_order.html', content)

    @method_decorator(check_auth)
    def post(self, request):
        user_id = request.session.get("user_id")
        user = UserProfile.objects.filter(id=user_id).first()
        cart_id = request.POST.getlist('checkbox')
        order_list = ShopCart.objects.filter(id__in=cart_id)
        cart_id = '/'.join(cart_id)
        content = {'order_list': order_list, 'user': user, 'cart_id': cart_id}
        """
        这里暂时把提交的购物车的放入到session中
        """
        request.session['cart_id'] = cart_id
        return render(request, 'shop_cart/place_order.html', content)


class MyCartView(View):
    """购物车页面"""

    @method_decorator(check_auth)
    def get(self, request):
        user_id = request.session.get('user_id')
        cart_info = ShopCart.objects.filter(user_id=user_id).order_by('-id')
        content = {"cart_info": cart_info}
        return render(request, 'shop_cart/cart.html', content)

        # result = UseRedis.read_from_cache(user_id)
        #           if result is None:  # 构建数据结构为 result = {user_id:{'nid':nid, 'count': count}} 内层为cart的字典
        #               result = {}
        #               cart_info = {}
        #           else:
        #               data = result.get('user_id')
        #               if data.get('nid') == nid:
        #                   data['count'] = data.get('count') + count  # 计算同种商品的数量
        #                   UseRedis.write_to_cache(user_id, result)
        #           cart_info['nid'] = nid
        #           cart_info['count'] = count
        #           result['user_id'] = cart_info
        #           content = {'statue':200}

eshop/templates/shop_cart/cart.html
{% extends 'user_base.html' %}
{% block title %}
    天天生鲜－购物车
{% endblock title %}
{% block user_title %}
    购物车
{% endblock user_title %}
{% block user_center %}
{% endblock user_center %}
{% block user_content %}
    <form action="{% url 'shop_cart:order' %}" method="post">
        {% csrf_token %}
        <div class="total_count">全部商品<em>０</em>件</div>
        <ul class="cart_list_th clearfix">
            <li class="col01">商品名称</li>
            <li class="col02">商品单位</li>
            <li class="col03">商品价格</li>
            <li class="col04">数量</li>
            <li class="col05">小计</li>
            <li class="col06">操作</li>
        </ul>
        {% for item in cart_info %}
            <ul class="cart_list_td clearfix">$
                <li class="col01"><input type="checkbox" name="checkbox" checked="checked"
                                         value="{{ item.id }}"></li>
                <li class="col02"><img src="{{ MEDIA_URL }}{{ item.goods_info.goods_images }}"></li>
                <li class="col03">{{ item.goods_info.goods_name }}<br><em>{{ item.goods_info.goods_price }}元/{{ item.goods_info.goods_unit }}</em>
                </li>
                <li class="col04">{{ item.goods_info.goods_unit }}</li>
                <li class="col05"><em>{{ item.goods_info.goods_price }}</em>元</li>
                <li class="col06">
                    <div class="num_add">
                        <a href="javascript:;" class="add fl">+</a>
                        <input type="text" class="num_show fl" value="{{ item.count }}">
                        <input type="hidden" value="{{ item.goods_info.goods_stock }}">
                        <input type="hidden" class="update_cart_url"
                               value="{% url 'shop_cart:update_cart' item.goods_info.id %}">
                        <a href="javascript:;" class="minus fl">-</a>
                    </div>
                </li>
                <li class="col07"><em>0</em>元</li>
                <li class="col08"><a href="javascript:;">删除</a>
                    <input type="hidden" value="{% url 'shop_cart:delete_goods' item.goods_info.id %}">
                </li>
            </ul>
        {% endfor %}
        <ul class="settlements">
            <li class="col01"><input type="checkbox" name="" checked="checked"></li>
            <li class="col02">全选</li>
            <li class="col03">合计(不含运费)：<span>¥</span><em>０</em><br>共计<b class="total_num">０</b>件商品</li>
            <li class="col04"><input type="submit" value="去结算"></li>
        </ul>
    </form>
    <script>
        function format_num(num) {
            //格式化计算后的数据
            return parseFloat(new Number(num).toFixed(2));  // 计算每个商品的总价钱
        }
        function save_total_price(total_price) {
            //保存总的金额
            totalprice = format_num(total_price);
            $('.settlements .col03 em').text(totalprice);
        }
        function get_total_price() {
            // 计算购车中总的商品的价格
            var total_price = 0;  // 总价
            var total_num = 0;  // 总数量
            $('.cart_list_td').each(function (index) {
                var $li = $('.cart_list_td').eq(index).children();
                var checked = $li.eq(0).children().prop('checked');
                var goods_price = parseFloat($li.eq(4).children().text());  //获取商品的单价
                var goods_num = parseInt($li.eq(5).find('.num_show').val());  //获取商品的个数
                var min_price = format_num(goods_num * goods_price);  // 计算每个商品的总价钱
                $li.eq(6).children().text(min_price);
                if (checked) {
                    total_price = total_price + min_price;
                }
                total_num = index + 1;
            });
            save_total_price(total_price);
            var total_buy_num = $("input[name='checkbox']:checked").length;
            $('.settlements .col03 .total_num').text(total_buy_num); // 显示底部总的数量
            $('.total_count em').text(total_num);  // 显示顶部总的数量
        }
        $(function () {
            var $ul = $('.cart_list_td');
            var $total_checked =  $('.settlements .col01');
            get_total_price(); // 调用计算总商品价格的函数

            // 设定全选按钮的按钮的功能
           $total_checked.children().click(function () {
                var statue = $(this).prop('checked');
                $(':checkbox').prop('checked', statue);
                get_total_price();
            });
            //判断每个复选框的状态
            $(':checkbox').click(function () {
                var checked_size = $("input[name='checkbox']:checked").length;
                var total_checkbox_size = $("input[name='checkbox']").length;
                if (checked_size !== total_checkbox_size) {
                    $total_checked.prop('checked', false);
                } else {
                    $total_checked.prop('checked', true);
                }
                get_total_price();

            });
            //input 文本框失去焦点的时候
            function input_bur(ths) {
                var store = parseInt(ths.next().val());
                var input_num = ths.val();
                if (isNaN(input_num)) {
                    alert('请输入一个整数');
                    ths.val(1)
                } else if (input_num > store) {
                    alert('输入的最大数量超过了库存量');
                    ths.val(store);
                } else if (input_num < 1) {
                    alert('一个你也不买。。。');
                    ths.val(1);
                }
                var buy_num = ths.val();
                var update_cart_url = ths.parent().find('.update_cart_url').val();
                var data = {'buy_num': buy_num};
                $.get(update_cart_url, data, function (data) {
                    if (data.statue === "1") {
                        get_total_price()
                    }
                });
            }

            $ul.each(function (index) {
                var $li = $ul.eq(index).children();
                var $input_num = $li.eq(5).find('.num_show').blur(function () {
                    input_bur($(this))
                });

                $li.eq(5).find('.add').click(function () {
                    var input_num = parseInt($input_num.val());
                    $input_num.val(input_num + 1);
                    input_bur($input_num)
                });
                $li.eq(5).find('.minus').click(function () {
                    var input_num = parseInt($input_num.val());
                    $input_num.val(input_num - 1);
                    input_bur($input_num);
                });

            });
            //实现点击删除的时候删除购物车中的内容
            $ul.each(function (index) {
                var $delete = $ul.eq(index).children('.col08').children(":first-child");
                var delete_goods_url = $delete.next().val();
                $delete.click(function () {
                    var is_sure = confirm("确定要删除？")
                    if (is_sure) {
                        $.get(delete_goods_url, function (data) {
                            if (data.statue === '1') {
                                $delete.parent().parent().remove();
                                get_total_price();
                                {#                                location.href = '/shop/index/';#}
                            }
                        });
                    }
                });
            })
        });

    </script>
{% endblock user_content %}

<script>
    {#    $ul.each(function (index) {#}
    {#        // 检测每个checkbox的值根据值来进行总金额的计算#}
    {#        var $li = $ul.eq(index).children();#}
    {#        $li.eq(0).children().click(function () {#}
    {#            var mix_price = 0;#}
    {#            if ($(this).prop('checked')) {  // 选中这个商品的话#}
    {#                mix_price = parseFloat($li.eq(6).children().text()); // 获取到单件商品的小计价格#}
    {#                total_price = total_price + mix_price; // 计算减去后的总价格#}
    {#                total_num = total_num + 1;#}
    {#            } else { // 如果没有选中这个商品的话#}
    {#                mix_price = parseFloat($li.eq(6).children().text()); // 获取到单件商品的小计价格#}
    {#                total_price = total_price - mix_price; // 计算减去后的总价格#}
    {#                total_num = total_num - 1;#}
    {#                $total_checked.prop('checked', "");#}
    {#            }#}
    {#            save_total_price(total_price);#}
    {#            $bottom_total_num.text(total_num);#}
    {#        });#}
    {#    });#}
    {#    //全选按钮判断#}
    {#    $total_checked.click(function () {#}
    {#        var $check_box = $('input:checkbox');#}
    {#        total_price = 0;#}
    {#        total_num = 0;#}
    {#        if ($total_checked.prop('checked')) {#}
    {#            $check_box.prop('checked', 'true'); // 选中的check——box 全部设定为checked#}
    {#            get_total_price() // 调用计算总价格的函数#}
    {#        } else {#}
    {#            $check_box.prop('checked', ''); // 选中的check——box 全部设定为checked#}
    {#            $total_price.text(0);#}
    {#            $bottom_total_num.text(0);#}
    {#        }#}
    {#    });#}
    {##}
    {#    // 商品数量加件的操作#}
    {#    $ul.each(function (index) {#}
    {#        var $li = $ul.eq(index).children();#}
    {#        $li.eq(5).find('.add').click(function () {#}
    {#            // 这里还缺少一个库存的判断#}
    {#            //点击添加一个商品的#}
    {#            var current_num = parseInt($li.eq(5).find('.num_show').val());  //获取商品的个数#}
    {#            $li.eq(5).find('.num_show').val(current_num + 1); //单件商品的总个数加1#}
    {#            var mix_price = parseFloat($li.eq(6).children().text()); // 获取到单件商品的小计价格#}
    {#            var price = parseFloat($li.eq(4).children().text());  //获取商品的单价#}
    {#            mix_price = mix_price + price;#}
    {#            mix_price = format_num(mix_price);#}
    {#            $li.eq(6).children().text(mix_price); // 设定单件商品的小计价格#}
    {#            total_price = total_price + price; // 计算加一个单件商品后的总价格#}
    {#            save_total_price(total_price);#}
    {#            var add_cart_url = $li.eq(5).find('.add_cart_url').val();#}
    {#            send_ajax(add_cart_url, 1)#}
    {#        });#}
    {#        $li.eq(5).find('.minus').click(function () {#}
    {#            // 点击减去商品的时候#}
    {#            var current_num = parseInt($li.eq(5).find('.num_show').val());  //获取商品的个数#}
    {#            if (current_num <= 1) {#}
    {#                return#}
    {#            }#}
    {#            $li.eq(5).find('.num_show').val(current_num - 1); //单件商品的总个数减1#}
    {#            var mix_price = parseFloat($li.eq(6).children().text()); // 获取到单件商品的小计价格#}
    {#            var price = parseFloat($li.eq(4).children().text());  //获取商品的单价#}
    {#            mix_price = mix_price - price;#}
    {#            mix_price = format_num(mix_price);#}
    {#            $li.eq(6).children().text(mix_price); //设定单件商品的小计价格#}
    {#            total_price = total_price - price; // 计算减一个单件商品后的总价格#}
    {#            save_total_price(total_price);#}
    {#            var add_cart_url = $li.eq(5).find('.add_cart_url').val(); // 找到对应的url#}
    {#            send_ajax(add_cart_url, -1)#}
    {#        });#}
    {#    });#}
    {#    })#}
    {#    ;#}
</script>


{#        function get_total_price() {#}
{#            // 计算购车中总的商品的价格#}
{#            var total_price = 0;  // 总价#}
{#            var total_num = 0;  // 总数量#}
{#            $ul.each(function (index) {#}
{#                var $li = $ul.eq(index).children();#}
{#                var checked = $li.eq(0).children().prop('checked');#}
{#                var goods_price = parseFloat($li.eq(4).children().text());  //获取商品的单价#}
{#                var goods_num = parseInt($li.eq(5).find('.num_show').val());  //获取商品的个数#}
{#                var min_price = format_num(goods_num * goods_price);  // 计算每个商品的总价钱#}
{#                $li.eq(6).children().text(min_price);#}
{#                if (checked) {#}
{#                    total_price = total_price + min_price;#}
{#                }#}
{#                total_num = index + 1;#}
{#            });#}
{#            save_total_price(total_price);#}
{#            var total_buy_num = $("input[name='checkbox']:checked").length;#}
{#            $bottom_total_num.text(total_buy_num); // 显示底部总的数量#}
{#            $top_total_num.text(total_num);  // 显示顶部总的数量#}
{#        }#}

eshop/templates/shop_cart/place_order.html
{% extends 'user_base.html' %}
{% block title %}
    天天生鲜－订单中心
{% endblock title %}
{% block user_title %}
    订单中心
{% endblock user_title %}
{% block user_center %}
{% endblock user_center %}
{% block user_content %}


    <h3 class="common_title">确认收货地址</h3>

    <div class="common_list_con clearfix">
        <dl>
            <dt>寄送到：</dt>
            <dd><input type="radio" name="" checked="">{{ user.city }}&nbsp;&nbsp;&nbsp;{{ user.address }}&nbsp;&nbsp;&nbsp;({{ user.username }}收&nbsp;&nbsp;&nbsp;{{ user.telephone }})
                <br> 北京市 海淀区 东北旺西路8号中关村软件园 （李思 收） 182****7528
            </dd>
        </dl>
        <a href="user_center_site.html" class="edit_site">编辑收货地址</a>

    </div>

    <h3 class="common_title">支付方式</h3>
    <div class="common_list_con clearfix">
        <div class="pay_style_con clearfix">
            <input type="radio" name="pay_style" checked>
            <label class="cash">货到付款</label>
            <input type="radio" name="pay_style">
            <label class="weixin">微信支付</label>
            <input type="radio" name="pay_style">
            <label class="zhifubao"></label>
            <input type="radio" name="pay_style">
            <label class="bank">银行卡支付</label>
        </div>
    </div>

    <h3 class="common_title">商品列表</h3>

    <div class="common_list_con clearfix">
        <ul class="goods_list_th clearfix">
            <li class="col01">商品名称</li>
            <li class="col02">商品单位</li>
            <li class="col03">商品价格</li>
            <li class="col04">数量</li>
            <li class="col05">小计</li>
        </ul>
        {% for item in order_list %}
            <ul class="goods_list_td clearfix">
                <li class="col01">{{ forloop.counter }}</li>
                <li class="col02"><img src="{{ MEDIA_URL }}{{ item.goods_info.goods_images }}"></li>
                <li class="col03">{{ item.goods_info.goods_name|truncatechars:10 }}</li>
                <li class="col04">{{ item.goods_info.goods_unit }}</li>
                <li class="col05"><em>{{ item.goods_info.goods_price }}</em>元</li>
                <li class="col06">{{ item.count }}</li>
                <li class="col07"><em>0</em>元</li>
            </ul>
        {% endfor %}
    </div>

    <h3 class="common_title">总金额结算</h3>
    <form action="{% url 'shop_order:order' %}" method="post">
    {% csrf_token %}
        <div class="common_list_con clearfix">
            <div class="settle_con">
                <div class="total_goods_count">共<em>2</em>件商品，总金额<b>42.60</b>元</div>
                <div class="transit">运费：<b>10</b>元</div>
                <div class="total_pay">实付款：<b>0</b>元</div>
                <input type="hidden" name="cart_id" value="{{ cart_id }}">
            </div>
        </div>
        <div class="order_submit clearfix">
            <input type="submit" value="提交订单">
        </div>
    </form>
    <div class="popup_con">
        <div class="popup">
            <p>订单提交成功！</p>
        </div>

        <div class="mask"></div>
    </div>
    <script type="text/javascript">
        $('#order_btn').click(function () {
            localStorage.setItem('order_finish', 2);

            $('.popup_con').fadeIn('fast', function () {

                setTimeout(function () {
                    $('.popup_con').fadeOut('fast', function () {
{#                        window.location.href = 'index.html';#}
                    });
                }, 3000)

            });
        });
    </script>
    <script>
        $(function () {
            var $ul = $('.goods_list_td');
            var total_price = 0;
            $ul.each(function () {
                var price = parseFloat($(this).find('.col05 em').text());
                var buy_num = parseInt($(this).find('.col06').text());
                min_price = parseFloat(new Number(price * buy_num).toFixed(2));
                $(this).find('.col07 em').text(min_price);
                total_price = total_price + min_price;
            });
            total_price = parseFloat(new Number(total_price).toFixed(2));
            $('.common_list_con .settle_con .total_goods_count b').text(total_price);
            var yun_fei = parseFloat($('.common_list_con .settle_con .transit b').text());
            $('.common_list_con .settle_con .total_pay b').text(total_price + yun_fei);
        });
    </script>
{% endblock user_content %}