eshop/eshop/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/', include('users.urls', namespace='user')),
    url(r'^shop/', include('shop.urls', namespace='shop')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^search/', include('haystack.urls')),
    url(r'^shop_cart/', include('shop_cart.urls', namespace='shop_cart')),
    url(r'^shop_order/', include('shop_order.urls', namespace='shop_order')),
    # url('^search/$', MySearchView.as_view())
]


















# if settings.DEBUG:
#    urlpatterns += patterns('', url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT }),
#         url(r'^static/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.STATIC_ROOT}), )

eshop/shop/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2017/7/5 19:01
# @Author  : zhl
# @Site    : 
# @File    : urls.py
# @Software: PyCharm
from django.conf.urls import url
from shop import views
from .search_view import MySearchView
urlpatterns = [
    url(r'^index/$', views.IndexView.as_view(), name='index'),
    url(r'^detail/(?P<nid>\d*)/$', views.DetailView.as_view(), name='detail'),
    url(r'^list/(?P<nid>\d*)/$', views.ListView.as_view(), name='list'),
    url(r'^list_check/(?P<nid>\d*)-(?P<current_page>\d*)-(?P<ordering>\d*)/$', views.ListCheckView.as_view(), name='list_check'),

]

eshop/shop_cart/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2017/7/11 11:39
# @Author  : zhl
# @Site    : 
# @File    : urls.py
# @Software: PyCharm
from django.conf.urls import url

from shop_cart import views
urlpatterns = [
    url(r'^add_cart/(?P<nid>\d*)/$', views.AddCartView.as_view(), name='add_cart'),
    url(r'^update_cart/(?P<nid>\d*)/$', views.UpdateCartview.as_view(), name='update_cart'),
    url(r'^delete_goods/(?P<nid>\d*)/$', views.DeleteGoodsView.as_view(), name='delete_goods'),
    url(r'^order/$', views.OrderView.as_view(), name='order'),
    url(r'^my_cart/$', views.MyCartView.as_view(), name='my_cart'),
]

eshop/shop/models.py
from django.db import models

from tinymce.models import HTMLField


# Create your models here.
class GoodsCategory(models.Model):
    category_name = models.CharField(max_length=20, verbose_name="商品分类")
    is_delete = models.BooleanField(default=0, verbose_name="是否删除")

    class Meta:
        verbose_name = '商品分类'
        verbose_name_plural = verbose_name
        ordering = ('id',)

    def __str__(self):
        return self.category_name


class GoodsArea(models.Model):
    city_name = models.CharField(max_length=20, verbose_name='商品产地')

    class Meta:
        verbose_name = '商品产地'
        verbose_name_plural = verbose_name
        ordering = ('id',)

    def __str__(self):
        return self.city_name


class GoodsInfo(models.Model):
    goods_name = models.CharField(max_length=30, verbose_name='商品名称')
    goods_images = models.ImageField(upload_to='goods/%Y/%m/%d', verbose_name='商品图片地址')
    goods_price = models.DecimalField(max_digits=5, decimal_places=2)
    goods_click = models.IntegerField(verbose_name='商品点击量')
    goods_unit = models.CharField(max_length=10, verbose_name='商品单位')
    is_delete = models.BooleanField(default=0, verbose_name='是否删除')
    goods_desc = models.TextField(verbose_name='商品描述')
    goods_stock = models.IntegerField(default=100, verbose_name='商品库存')
    goods_detail = HTMLField()
    goods_category = models.ForeignKey('GoodsCategory', verbose_name='商品分类')
    goods_city = models.ForeignKey('GoodsArea', verbose_name='商品产地', null=True)

    class Meta:
        verbose_name = '商品信息'
        verbose_name_plural = verbose_name
        ordering = ('id',)

    def __str__(self):
        return self.goods_name

eshop/shop/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.views.generic import View
from django.core.paginator import Paginator, InvalidPage, PageNotAnInteger

from .models import GoodsCategory, GoodsInfo
from utils.use_redis import UseRedis
from utils.my_logger import logger

# from utils.my_print import my_print
# 全局的数据库查询使用的是 查询集的惰性 和 缓存
goods_category_list = GoodsCategory.objects.all()
category_list = goods_category_list.values('id', 'category_name')


# cart_num = ShopCart.objects.

# Create your views here.

class IndexView(View):
    """index首页视图"""

    def get(self, request):
        goods_list = []
        goods_num = 0  # 用户购物车中的商品的数量
        for item in goods_category_list:
            click_num = item.goodsinfo_set.order_by('-goods_click')[0:4]
            new_list = item.goodsinfo_set.order_by('-id')[0:4]
            goods_list.append({'click_num': click_num, 'new_list': new_list, 'goods_category': item})
        user_id = request.session.get('user_id')
        if user_id:
            goods_num = UseRedis.read_from_cache(user_id, "total_num")
            if goods_num is None:
                goods_num = 0
        content = {'goods_list': goods_list, 'category_list': category_list, 'goods_num': goods_num}
        return render(request, 'shop/index.html', content)


class DetailView(View):
    """详情页视图"""

    def get(self, request, nid): # nid  商品的id
        goods_num = 0  # 用户购物车中的商品的数量
        user_id = request.session.get('user_id')  # 获取用户的id 用来区别不同的用户 存入redis'
        goods_info = GoodsInfo.objects.filter(id=nid).first()
        if request.is_ajax():  # 查询商品库存
            data = goods_info.goods_stock
            return JsonResponse({'data': data})
        goods_info.goods_click = goods_info.goods_click + 1  # 商品的点击量加1
        goods_info.save()

        recently_browsed = UseRedis.read_from_cache(user_id, 'recently_browsed')
        if recently_browsed is None:
            recently_browsed = []
        if nid in recently_browsed:
            recently_browsed.remove(nid)
        recently_browsed.append(nid)
        if len(recently_browsed) > 5:
            recently_browsed.pop(0)
        if user_id:
            UseRedis.write_to_cache(user_id, 'recently_browsed', recently_browsed)
        if user_id:
            goods_num = UseRedis.read_from_cache(user_id, "total_num")
            if goods_num is None:
                goods_num = 0
        content = {'goods_info': goods_info, 'category_list': category_list, 'goods_num': goods_num}
        return render(request, 'shop/detail.html', content)


class ListCheckView(View):
    """list页视图"""

    def get(self, request, nid, current_page="1", ordering="0"):
        # 判断采用那种方式进行数据的检索
        goods_num = 0  # 用户购物车中的商品的数量
        oid, order = self.get_order(ordering, request)  # 检索商品
        current_page = int(current_page)
        goods_category = goods_category_list.filter(id=nid).first()
        goods_info = GoodsInfo.objects.filter(goods_category=goods_category).order_by(order)
        # 实现分页
        page = Paginator(goods_info, 2)
        current_goods_obj = page.page(current_page)
        page_rang = page.page_range
        # 获取用户购物车中的数量
        user_id = request.session.get('user_id')
        if user_id:
            goods_num = UseRedis.read_from_cache(user_id, "total_num")
            if goods_num is None:
                goods_num = 0
        # 构建字典返回数据
        content = {'category_list': category_list, 'goods_category': goods_category,
                   'current_goods_obj': current_goods_obj, 'page_rang': page_rang,
                   'current_page': current_page, 'ordering': ordering, 'page': page,
                   "oid": oid, 'goods_num': goods_num}
        response = render(request, 'shop/list.html', content)
        return response

    def get_order(self, ordering, request):
        """排序检索方法"""
        order = '-id'  # 默认的排序的方式
        oid = '1'
        if ordering == "0" or "":
            order = "-id"
        elif ordering == "1":
            # 根据get上来的值来判断采用那种方式进行排序
            oid = request.GET.get('oid')
            if oid == '1':
                order = '-goods_price'
                oid = '2'
            elif oid == '2':
                order = 'goods_price'
                oid = '1'
        elif ordering == "2":
            order = '-goods_click'
        return oid, order


class ListView(View):
    """list页视图"""

    def get(self, request, nid):
        # 判断采用那种方式进行数据的检索
        # 检索商品 默认的是返回当前页面  1 第一页
        goods_num = 0  # 用户购物车中的商品的数量
        current_page = 1
        goods_category = goods_category_list.filter(id=nid).first()
        goods_info = GoodsInfo.objects.filter(goods_category=goods_category).order_by('-id')
        # 实现分页 默认的是5页
        page = Paginator(goods_info, 2)

        current_goods_obj = page.page(current_page)
        page_rang = page.page_range
        # 获取用户购物车中的数量
        user_id = request.session.get('user_id')
        if user_id:
            goods_num = UseRedis.read_from_cache(user_id, "total_num")
            if goods_num is None:
                goods_num = 0
        # 构建字典返回数据  这里返回的是0 因为0被设置为默认的排序方式
        content = {'category_list': category_list, 'goods_category': goods_category,
                   'current_goods_obj': current_goods_obj, 'page_rang': page_rang,
                   'current_page': current_page, 'ordering': "0", 'page': page,
                   'oid': '1', 'goods_num': goods_num}
        return render(request, 'shop/list.html', content)

# class DetailView(View):
#     """采用session实现用户的浏览记录"""
#
#     def get(self, request, nid):
#         goods_info = GoodsInfo.objects.filter(id=nid).first()
#         if request.is_ajax():  # 查询商品库存
#             data = goods_info.goods_stock
#             return JsonResponse({'data': data})
#         goods_info.goods_click = goods_info.goods_click + 1  # 商品的点击量加1
#         goods_info.save()
#         content = {'goods_info': goods_info, 'category_list': category_list}
#         recently_browsed =request.session.get("recently_browsed","").split('/')
#         for item in recently_browsed:
#             if len(item) == 0:
#                 recently_browsed.remove(item)
#         if nid in recently_browsed:
#             recently_browsed.remove(nid)
#         recently_browsed.append(nid)
#         if len(recently_browsed) > 5:
#             recently_browsed.pop(0)
#         recently_browsed = "/".join(recently_browsed)
#         request.session['recently_browsed'] = recently_browsed
#         request.session.set_expiry(None)
#         return render(request, 'shop/detail.html', content)

eshop/templates/shop/detail.html
{% extends 'shop_base.html' %}
{% block shop_js %}
    <script type="text/javascript" src="{{ STATIC_URL }}js/detail.js"></script>
{% endblock shop_js %}
{% block index_content %} {{ block.super }}
    <div class="breadcrumb">
        <a href="{% url 'shop:index' %}">全部分类</a>
        <span>></span>
        <a href="{% url 'shop:list' goods_info.goods_category.id %}">{{ goods_info.goods_category }}</a>
        <span>></span>
        <a href="#">商品详情</a>
    </div>

    <div class="goods_detail_con clearfix">
        <div class="goods_detail_pic fl"><img src="{{ MEDIA_URL }}{{ goods_info.goods_images }}"></div>
        <div class="goods_detail_list fr">
            <h3>{{ goods_info.goods_name }}</h3>
            <p>{{ goods_info.goods_desc }}</p>
            <div class="prize_bar">
                <span class="show_pirze">¥<em>{{ goods_info.goods_price }}</em></span>
                <span class="show_unit">单  位：{{ goods_info.goods_unit }}</span>
                <span id="goods_id">{{ goods_info.id }}</span>
            </div>
            <div class="goods_num clearfix">
                <div class="num_name fl">数 量：</div>
                <div class="num_add fl">
                    <input type="text" class="num_show fl" value="1">
                    <input type="hidden" name="hidden" id="add_cart_url"
                           value="{% url 'shop_cart:add_cart' goods_info.id %}">
                    <a href="javascript:;" class="add fr">+</a>
                    <a href="javascript:;" class="minus fr">-</a>
                </div>
                <span class="show_kucun"
                      style="margin-left: 20px;margin-top: 15px; display: inline-block">库 存：<em>{{ goods_info.goods_stock }}</em></span>
            </div>
            <div class="total">总价：<em>{{ goods_info.goods_price }}元</em></div>
            <div class="operate_btn">
                <a href="javascript:;" class="buy_btn">立即购买</a>
                <a href="javascript:;" class="add_cart" id="add_cart">加入购物车</a>
            </div>
        </div>
    </div>

    <div class="main_wrap clearfix">
        <div class="l_wrap fl clearfix">
            <div class="new_goods">
                <h3>新品推荐</h3>
                <ul>
                    <li>
                        <a href="#"><img src="{{ STATIC_URL }}images/goods/goods001.jpg"></a>
                        <h4><a href="#">进口柠檬</a></h4>
                        <div class="prize">￥3.90</div>
                    </li>
                    <li>
                        <a href="#"><img src="{{ STATIC_URL }}images/goods/goods002.jpg"></a>
                        <h4><a href="#">玫瑰香葡萄</a></h4>
                        <div class="prize">￥16.80</div>
                    </li>
                </ul>
            </div>
        </div>

        <div class="r_wrap fr clearfix">
            <ul class="detail_tab clearfix">
                <li class="active">商品介绍</li>
                <li>评论</li>
            </ul>

            <div class="tab_content">
                <dl>
                    <dt>商品详情：</dt>
                    <dd>
                        {{ goods_info.goods_detail|safe }}
                    </dd>
                </dl>
            </div>

        </div>
    </div>

    <div class="add_jump"></div>

    <script type="text/javascript">
    </script>

{% endblock index_content %}

eshop/templates/shop/index.html
{% extends 'shop_base.html' %}

{% block index_content %}
    <div class="navbar_con">
        <div class="navbar">
            <h1 class="fl">全部商品分类</h1>
            <ul class="navlist fl">
                <li><a href="">首页</a></li>
                <li class="interval">|</li>
                <li><a href="">手机生鲜</a></li>
                <li class="interval">|</li>
                <li><a href="">抽奖</a></li>
            </ul>
        </div>
    </div>

    <div class="center_con clearfix">
        <ul class="subnav fl">
            <li><a href="{% url 'shop:list' category_list.0.id %}" class="fruit">{{ category_list.0.category_name }}</a></li>
            <li><a href="{% url 'shop:list' category_list.1.id %}" class="seafood">{{ category_list.1.category_name }}</a></li>
            <li><a href="{% url 'shop:list' category_list.2.id %}" class="meet">{{ category_list.2.category_name }}</a></li>
            <li><a href="{% url 'shop:list' category_list.3.id %}" class="egg">{{ category_list.3.category_name }}</a></li>
            <li><a href="{% url 'shop:list' category_list.4.id %}" class="vegetables">{{ category_list.4.category_name }}</a></li>
            <li><a href="{% url 'shop:list' category_list.5.id %}" class="ice">{{ category_list.5.category_name }}</a></li>
        </ul>

        <div class="slide fl">
            <ul class="slide_pics">
                <li><img src="{{ STATIC_URL }}images/slide.jpg" alt="幻灯片"></li>
                <li><img src="{{ STATIC_URL }}images/slide02.jpg" alt="幻灯片"></li>
                <li><img src="{{ STATIC_URL }}images/slide03.jpg" alt="幻灯片"></li>
                <li><img src="{{ STATIC_URL }}images/slide04.jpg" alt="幻灯片"></li>
            </ul>
            <div class="prev"></div>
            <div class="next"></div>
            <ul class="points"></ul>
        </div>
        <div class="adv fl">
            <a href="#"><img src="{{ STATIC_URL }}images/adv01.jpg"></a>
            <a href="#"><img src="{{ STATIC_URL }}images/adv02.jpg"></a>
        </div>
    </div>
    {% for item in goods_list %}
        <div class="list_model">
            <div class="list_title clearfix">
                <h3 class="fl" id="model0{{ forloop.counter }}">{{ item.goods_category }}</h3>
                <div class="subtitle fl">
                    <span>|</span>
                    {% for item in item.click_num %}
                        <a href="{% url 'shop:detail' item.id %}">{{ item.goods_name }}</a>
                    {% endfor %}
                </div>
                <a href="{% url 'shop:list' item.goods_category.id %}" class="goods_more fr" id="fruit_more">查看更多 ></a>
            </div>


                <div class="goods_con clearfix">
                    <div class="goods_banner fl"><img src="{{ STATIC_URL }}images/banner0{{ forloop.counter }}.jpg"></div>
                    <ul class="goods_list fl">
                        {% for item in item.new_list %}
                         <li>
                            <h4><a href="{% url 'shop:detail' item.id %}">{{ item.goods_name }}</a></h4>
                            <a href="{% url 'shop:detail' item.id %}"><img src="{{ MEDIA_URL }}{{ item.goods_images }}"></a>
                            <div class="prize">¥ {{ item.goods_price }}</div>
                        </li>
                        {% endfor %}

                    </ul>
                </div>
                </div>

    {% endfor %}
    <script type="text/javascript" src="{{ STATIC_URL }}js/slideshow.js"></script>
    <script type="text/javascript">
        BCSlideshow('focuspic');
        var oFruit = document.getElementById('fruit_more');
        var oShownum = document.getElementById('show_count');

        var hasorder = localStorage.getItem('order_finish');

        if (hasorder) {
            oShownum.innerHTML = '2';
        }

        oFruit.onclick = function () {
            window.location.href = 'list.html';
        }
    </script>

{% endblock index_content %}



eshop/templates/shop/list.html
{% extends 'shop_base.html' %} {% load simpletag %}
{% block shop_js %}
    <script type="text/javascript" src="{{ STATIC_URL }}js/list.js"></script>
{% endblock shop_js %}

{% block index_content %} {{ block.super }}

    <div class="breadcrumb">
        <a href="{% url 'shop:index' %}">全部分类</a>
        <span>></span>
        <a href="#">{{ goods_category.category_name }}</a>
    </div>

    <div class="main_wrap clearfix">
        <div class="l_wrap fl clearfix">
            <div class="new_goods">
                <h3>新品推荐</h3>
                <ul>
                    <li>
                        <a href="#"><img src="{{ STATIC_URL }}images/goods/goods001.jpg"></a>
                        <h4><a href="#">进口柠檬</a></h4>
                        <div class="prize">￥3.90</div>
                    </li>
                    <li>
                        <a href="#"><img src="{{ STATIC_URL }}images/goods/goods002.jpg"></a>
                        <h4><a href="#">玫瑰香葡萄</a></h4>
                        <div class="prize">￥16.80</div>
                    </li>
                </ul>
            </div>
        </div>

        <div class="r_wrap fr clearfix">
            <div class="sort_bar">
                <a href="{% url 'shop:list_check' goods_category.id 1 0 %}" {% if ordering == "0" %}
                   class="active" {% endif %}>默认</a>
                <a href="{% url 'shop:list_check' goods_category.id 1 1 %}?oid={{ oid }}" {% if ordering == "1" %}
                   class="active" {% endif %}>价格</a>
                <a href="{% url 'shop:list_check' goods_category.id 1 2 %}" {% if ordering == "2" %}
                   class="active" {% endif %}>人气</a>
            </div>

            <ul class="goods_type_list clearfix">
                {% for item in current_goods_obj %}
                    <li>
                        <a href="{% url 'shop:detail' item.id %}"><img src="{{ MEDIA_URL }}{{ item.goods_images }}"></a>
                        <h4><a href="{% url 'shop:detail' item.id %}">{{ item.goods_name }}</a></h4>
                        <div class="operate">
                            <span class="prize">￥{{ item.goods_price }}</span>
                            <span class="unit">{{ item.goods_price }}/{{ item.goods_unit }}/点击:{{ item.goods_click }}</span>
                            <span id="add_url">{% url 'shop_cart:add_cart' item.id %}</span>
                            <a href="#" class="add_goods" title="加入购物车"></a>
                        </div>
                    </li>
                {% endfor %}
            </ul>

            <div class="pagenation">
                {% if current_goods_obj.has_previous %}

                    <a href="{% url 'shop:list_check' goods_category.id 1 ordering %}"
                       style="background-color: #5bc0de">
                        <<</a>
                    <a href="{% url 'shop:list_check' goods_category.id current_goods_obj.previous_page_number ordering %}"
                       style="background-color: #5bc0de"> 上一页 </a> {% else %}
                    <a>
                        << </a>
                    <a> 上一页 </a> {% endif %} {% for current in page_rang %}
                {% paginator goods_category.id current ordering current_page page %} {% endfor %}
                {% if current_goods_obj.has_next %}
                    <a href="{% url 'shop:list_check' goods_category.id current_goods_obj.next_page_number ordering %}"
                       style="background-color: #5bc0de"> 下一页 </a>
                    <a href="{% url 'shop:list_check' goods_category.id page.num_pages ordering %}"
                       style="background-color: #5bc0de">
                        << </a>
                {% else %}
                    <a> 下一页 </a>
                    <a>
                        << </a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock index_content %}